- name: Run Backend API
  community.docker.docker_container:
    name: simple-api
    image: axlz/tp-devops-simple-api:latest
    networks:
      - name: app-network
    env:
      DATABASE_HOST: database
      DATABASE_PASSWORD: pwd
    recreate: yes
    pull: true
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
